FROM jenkins/jenkins:lts

USER root

# Install Docker inside Jenkins container
RUN apt-get update && apt-get install -y docker.io && \
    apt-get clean

# Allow Jenkins user to run Docker commands
RUN usermod -aG docker jenkins

# Install Jenkins plugins
RUN /usr/local/bin/install-plugins.sh git docker-workflow pipeline-stage-view

USER jenkins