pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Manel-Rejeb/NewsCrawler.git' 
            }
        }

        stage('Build and Start Containers') {
            steps {
                sh 'docker-compose down'
                sh 'docker-compose up --build -d'  # Build and start all services
            }
        }

        stage('Run Tests') {
            steps {
                // Add your test steps here
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                // Deploying the services
                echo 'Deploying to production...'
            }
        }
    }

    post {
        success {
            echo "Deployment Successful!"
        }
        failure {
            echo "Deployment Failed!"
        }
    }
}
